export const students = [
  { id: 1, name: "Ali", age: 35, email: "ali@gmail.com", class: "MBA" },
  {
    id: 2,
    name: "Fouad",
    age: 25,
    email: "fouad@gmail.com",
    class: "Javascript",
  },
  {
    id: 3,
    name: "Delia DuBuque",
    age: 39,
    email: "tiana.vonrueden-runte@hotmail.com",
    class: "Business Administration",
  },
  {
    id: 4,
    name: "Kimberly Stark",
    age: 31,
    email: "jaylan_wisozk@yahoo.com",
    class: "MBA",
  },
  {
    id: 5,
    name: "Maria Haley",
    age: 23,
    email: "norris.stamm@yahoo.com",
    class: "Electrical Engineering",
  },
  {
    id: 6,
    name: "Ana Denesik",
    age: 22,
    email: "jessyca60@yahoo.com",
    class: "Mechanical Engineering",
  },
  {
    id: 7,
    name: "Noel Osinski",
    age: 38,
    email: "iliana_collins@gmail.com",
    class: "Business Administration",
  },
  {
    id: 8,
    name: "Timothy Pfeffer",
    age: 27,
    email: "percy31@gmail.com",
    class: "MBA",
  },
  {
    id: 9,
    name: "Ross Walker",
    age: 24,
    email: "tobin_trantow14@yahoo.com",
    class: "MBA",
  },
  {
    id: 10,
    name: "Lydia West",
    age: 18,
    email: "kiarra_jaskolski61@yahoo.com",
    class: "Business Administration",
  },
  {
    id: 11,
    name: "Ben Reinger MD",
    age: 35,
    email: "jayda_homenick-sanford83@hotmail.com",
    class: "Electrical Engineering",
  },
  {
    id: 12,
    name: "Renee Bayer",
    age: 25,
    email: "mallie32@yahoo.com",
    class: "Arts & Humanities",
  },
  {
    id: 13,
    name: "Derek Torphy",
    age: 33,
    email: "freddy_kihn@gmail.com",
    class: "Business Administration",
  },
  {
    id: 14,
    name: "Arnold Carroll",
    age: 26,
    email: "beau75@gmail.com",
    class: "Electrical Engineering",
  },
  {
    id: 15,
    name: "Verna Hessel",
    age: 30,
    email: "marlon.cummerata@yahoo.com",
    class: "Business Administration",
  },
  {
    id: 16,
    name: "Lowell Davis",
    age: 40,
    email: "johathan_hegmann30@hotmail.com",
    class: "MBA",
  },
  {
    id: 17,
    name: "Vickie Mosciski",
    age: 28,
    email: "gabriella95@yahoo.com",
    class: "Computer Science",
  },
  {
    id: 18,
    name: "Kate Keebler",
    age: 21,
    email: "geo81@yahoo.com",
    class: "Mechanical Engineering",
  },
  {
    id: 19,
    name: "Kirk Cole",
    age: 39,
    email: "abbigail39@gmail.com",
    class: "Mechanical Engineering",
  },
  {
    id: 20,
    name: "Dr. Israel Medhurst",
    age: 31,
    email: "haskell_jast@gmail.com",
    class: "Electrical Engineering",
  },
  {
    id: 21,
    name: "Homer Smitham",
    age: 23,
    email: "ruben_mohr92@hotmail.com",
    class: "Computer Science",
  },
  {
    id: 22,
    name: "Elvira Pacocha",
    age: 39,
    email: "gladyce.mcglynn64@yahoo.com",
    class: "Javascript",
  },
  {
    id: 23,
    name: "Marcos Wolf",
    age: 23,
    email: "jordyn.murray@hotmail.com",
    class: "Javascript",
  },
  {
    id: 24,
    name: "Mr. Dexter Nolan",
    age: 22,
    email: "marilie_romaguera3@yahoo.com",
    class: "MBA",
  },
  {
    id: 25,
    name: "Nicolas Lebsack",
    age: 26,
    email: "julien86@yahoo.com",
    class: "Business Administration",
  },
  {
    id: 26,
    name: "Muriel Dickens DVM",
    age: 23,
    email: "frieda.rath96@gmail.com",
    class: "Arts & Humanities",
  },
  {
    id: 27,
    name: "Abel Hills",
    age: 36,
    email: "isabelle.barton@yahoo.com",
    class: "Arts & Humanities",
  },
  {
    id: 28,
    name: "Andres Fadel",
    age: 25,
    email: "jerry_hermann@hotmail.com",
    class: "Computer Science",
  },
  {
    id: 29,
    name: "Al Yost",
    age: 19,
    email: "gardner92@yahoo.com",
    class: "Javascript",
  },
  {
    id: 30,
    name: "Miss Nadine Willms",
    age: 39,
    email: "janie64@gmail.com",
    class: "Electrical Engineering",
  },
  {
    id: 31,
    name: "Eleanor Flatley",
    age: 37,
    email: "trudie25@yahoo.com",
    class: "Electrical Engineering",
  },
  {
    id: 32,
    name: "Arthur Braun DVM",
    age: 29,
    email: "aisha18@gmail.com",
    class: "Javascript",
  },
  {
    id: 33,
    name: "Bradford Quigley",
    age: 18,
    email: "noemi_sipes@yahoo.com",
    class: "Electrical Engineering",
  },
  {
    id: 34,
    name: "Sarah Nader",
    age: 24,
    email: "howard.carroll@gmail.com",
    class: "Javascript",
  },
  {
    id: 35,
    name: "Bryant White",
    age: 34,
    email: "holly.leffler@yahoo.com",
    class: "Business Administration",
  },
  {
    id: 36,
    name: "Sadie Ryan",
    age: 26,
    email: "deondre_upton@gmail.com",
    class: "Computer Science",
  },
  {
    id: 37,
    name: "Brendan Gusikowski",
    age: 19,
    email: "jena14@hotmail.com",
    class: "Computer Science",
  },
  {
    id: 38,
    name: "Michele Romaguera",
    age: 22,
    email: "sarah.bayer93@hotmail.com",
    class: "MBA",
  },
  {
    id: 39,
    name: "Preston Walker",
    age: 27,
    email: "sean.berge67@hotmail.com",
    class: "Business Administration",
  },
  {
    id: 40,
    name: "Mae Kreiger",
    age: 25,
    email: "buck46@hotmail.com",
    class: "MBA",
  },
  {
    id: 41,
    name: "Clint Cassin",
    age: 22,
    email: "harmon.mann57@yahoo.com",
    class: "Arts & Humanities",
  },
  {
    id: 42,
    name: "Felix Denesik",
    age: 44,
    email: "alec_sporer@gmail.com",
    class: "Javascript",
  },
  {
    id: 43,
    name: "Rex Wehner",
    age: 26,
    email: "mark_hahn54@yahoo.com",
    class: "Javascript",
  },
  {
    id: 44,
    name: "Manuel Cole",
    age: 26,
    email: "giuseppe23@yahoo.com",
    class: "Arts & Humanities",
  },
  {
    id: 45,
    name: "Dr. Dave Little",
    age: 44,
    email: "clement.treutel@yahoo.com",
    class: "Electrical Engineering",
  },
  {
    id: 46,
    name: "Mrs. Johanna Osinski",
    age: 35,
    email: "maxwell.schmidt15@hotmail.com",
    class: "Javascript",
  },
  {
    id: 47,
    name: "Rolando McDermott",
    age: 45,
    email: "estella.wiegand67@gmail.com",
    class: "MBA",
  },
  {
    id: 48,
    name: "Melvin Bosco DVM",
    age: 44,
    email: "carrie_ruecker67@hotmail.com",
    class: "MBA",
  },
  {
    id: 49,
    name: "Mattie Hintz",
    age: 35,
    email: "mable_morar5@yahoo.com",
    class: "Computer Science",
  },
  {
    id: 50,
    name: "Cindy Hilpert",
    age: 22,
    email: "darryl_halvorson@hotmail.com",
    class: "Arts & Humanities",
  },
  {
    id: 51,
    name: "Leroy Sauer",
    age: 26,
    email: "arjun_wunsch@gmail.com",
    class: "Arts & Humanities",
  },
  {
    id: 52,
    name: "John Reinger",
    age: 25,
    email: "duncan19@yahoo.com",
    class: "Mechanical Engineering",
  },
  {
    id: 53,
    name: "Ian Lueilwitz",
    age: 20,
    email: "serenity.carter@gmail.com",
    class: "MBA",
  },
  {
    id: 54,
    name: "Miss Violet Schulist III",
    age: 19,
    email: "jamir.nolan19@gmail.com",
    class: "Computer Science",
  },
  {
    id: 55,
    name: "Vanessa Smitham",
    age: 24,
    email: "rebekah22@yahoo.com",
    class: "Computer Science",
  },
  {
    id: 56,
    name: "Dr. Wilfred Abshire",
    age: 30,
    email: "ciara68@gmail.com",
    class: "Javascript",
  },
  {
    id: 57,
    name: "Mr. Edmond Crooks",
    age: 38,
    email: "leanne_koelpin40@hotmail.com",
    class: "Computer Science",
  },
  {
    id: 58,
    name: "Duane Denesik",
    age: 39,
    email: "forest.rath@hotmail.com",
    class: "Arts & Humanities",
  },
  {
    id: 59,
    name: "Sherman Armstrong",
    age: 21,
    email: "cathy83@yahoo.com",
    class: "Business Administration",
  },
  {
    id: 60,
    name: "Ebony Murazik",
    age: 21,
    email: "hortense_swaniawski@hotmail.com",
    class: "Electrical Engineering",
  },
  {
    id: 61,
    name: "Mrs. Laurie Christiansen",
    age: 35,
    email: "eileen_quigley16@gmail.com",
    class: "Electrical Engineering",
  },
  {
    id: 62,
    name: "Bernadette Senger",
    age: 29,
    email: "hilbert.weimann37@hotmail.com",
    class: "Computer Science",
  },
  {
    id: 63,
    name: "Ms. Candace Hessel Jr.",
    age: 26,
    email: "jadon_kuphal-christiansen@hotmail.com",
    class: "Business Administration",
  },
  {
    id: 64,
    name: "Jacob Leuschke",
    age: 19,
    email: "hilma.rempel@gmail.com",
    class: "MBA",
  },
  {
    id: 65,
    name: "Dr. Herbert Wintheiser",
    age: 27,
    email: "faye.considine-schultz95@hotmail.com",
    class: "Business Administration",
  },
  {
    id: 66,
    name: "Kristi Weber-Beier",
    age: 22,
    email: "annabel.okeefe@yahoo.com",
    class: "Mechanical Engineering",
  },
  {
    id: 67,
    name: "Edward Bartell II",
    age: 38,
    email: "nyah53@yahoo.com",
    class: "Computer Science",
  },
  {
    id: 68,
    name: "Nicolas Wolf",
    age: 38,
    email: "oren.wyman@hotmail.com",
    class: "Electrical Engineering",
  },
  {
    id: 69,
    name: "Harry Schuster",
    age: 24,
    email: "reggie23@hotmail.com",
    class: "Javascript",
  },
  {
    id: 70,
    name: "Bessie Rosenbaum",
    age: 19,
    email: "vincenza.lebsack@gmail.com",
    class: "Electrical Engineering",
  },
  {
    id: 71,
    name: "Florence Donnelly",
    age: 18,
    email: "ora_ledner-mante@yahoo.com",
    class: "Electrical Engineering",
  },
  {
    id: 72,
    name: "Russell Wisoky",
    age: 44,
    email: "mathew.damore@yahoo.com",
    class: "Electrical Engineering",
  },
  {
    id: 73,
    name: "Thomas Haley",
    age: 30,
    email: "ruth39@gmail.com",
    class: "Mechanical Engineering",
  },
  {
    id: 74,
    name: "Olive Harris",
    age: 27,
    email: "darrin.sipes@yahoo.com",
    class: "Mechanical Engineering",
  },
  {
    id: 75,
    name: "Mrs. Debra Schowalter",
    age: 34,
    email: "marion.schinner@hotmail.com",
    class: "Mechanical Engineering",
  },
  {
    id: 76,
    name: "Kristina VonRueden",
    age: 24,
    email: "kristina_vonrueden@hotmail.com",
    class: "Arts & Humanities",
  },
  {
    id: 77,
    name: "Miss Jeanette Kihn",
    age: 30,
    email: "albert.kuhn@yahoo.com",
    class: "MBA",
  },
  {
    id: 78,
    name: "Darryl Kirlin",
    age: 20,
    email: "darryl.kirlin@hotmail.com",
    class: "Javascript",
  },
  {
    id: 79,
    name: "Miss Brenda Lehner",
    age: 33,
    email: "brenda.lehner@yahoo.com",
    class: "Mechanical Engineering",
  },
  {
    id: 80,
    name: "Mandy Lueilwitz",
    age: 20,
    email: "mandy.lueilwitz@gmail.com",
    class: "Computer Science",
  },
  {
    id: 81,
    name: "Mrs. Lynn Runolfsdottir",
    age: 30,
    email: "lynn.runolfsdottir@yahoo.com",
    class: "Electrical Engineering",
  },
  {
    id: 82,
    name: "Mr. Michael Wiegand",
    age: 32,
    email: "michael.wiegand@hotmail.com",
    class: "MBA",
  },
  {
    id: 83,
    name: "Jody Greenfelder",
    age: 37,
    email: "jody.greenfelder@gmail.com",
    class: "Mechanical Engineering",
  },
  {
    id: 84,
    name: "Mr. Mark Nitzsche",
    age: 38,
    email: "mark.nitzsche@yahoo.com",
    class: "Business Administration",
  },
  {
    id: 85,
    name: "Mr. Chris Schowalter",
    age: 27,
    email: "chris.schowalter@hotmail.com",
    class: "Arts & Humanities",
  },
  {
    id: 86,
    name: "Mrs. Brenda Kihn",
    age: 23,
    email: "brenda.kihn@gmail.com",
    class: "Javascript",
  },
  {
    id: 87,
    name: "Miss Frances Kihn",
    age: 39,
    email: "frances.kihn@yahoo.com",
    class: "MBA",
  },
  {
    id: 88,
    name: "Miss Lois Nitzsche",
    age: 32,
    email: "lois.nitzsche@hotmail.com",
    class: "Computer Science",
  },
  {
    id: 89,
    name: "Miss Jeanette Kihn",
    age: 35,
    email: "jeanette.kihn@gmail.com",
    class: "Electrical Engineering",
  },
  {
    id: 90,
    name: "Mr. Robert Schowalter",
    age: 25,
    email: "robert.schowalter@yahoo.com",
    class: "Business Administration",
  },
];
